### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by manuphatak** [manuphatak/2048#1]
# High priority
- [ ] create grid class and clean up the game api, remove the prototype extensions
- [ ] optimize some of the logic
- [ ] add tests for the middleware
- [ ] add some animations to the score box, similar to the original
- [ ] revisit some of the animations
- [ ] create a more impressive notice for the game over and game won messages
- [ ] implement the automatic new game logic, this is almost setup

---
# Lower priority
- [ ] mobile app with mobile friendly features -- swipes!  learn about react native
## Ideas to explore to make the game unique
- The 4x4 square is not hard coded.  
  - a board that changes size and shape with the game?
- achievements?
- add a new type of box that moves differently to make the game more interesting.  
  - a box that doesn't move?
  - a box that only moves one square?
  - a box that moves the wrong direction?
  - a box that pushes other boxes?
- make fun of pay to win?  maybe in a fork..
  - add powerups
  - add point currency
  - share with 3 friends to not ruin the game
